apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      label: binder
  template:
    metadata:
      labels:
        label: binder
    spec:
      containers:
        - name: bind9
          image: daemonmaster/bind9
          ports:
            - containerPort: 53
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: bind-service
  namespace: default
spec:
  type: NodePort
  selector:
    label: binder
  ports:
    - port: 53
      targetPort: 53
      nodePort: 30001
      protocol: UDP